### ISSUE TITLE
你怎么能拿Git来讲，明明大家都想讲

### ISSUE THREAD

**Issue by h1994st** [BigDipper7/Git-Test#1]
# Git
# Github

**Comment by iViolinSolo** [comment]
@h1994st  卧槽 原来你说的是这个issue 卧槽

**Comment by h1994st** [comment]
@BigDipper7 原来你才明白

**Comment by iViolinSolo** [comment]
@h1994st  真是才明白
我以为你们为什么说让看issue 我竟然没有发现

**Comment by iViolinSolo** [comment]
:sob: :+1:

**Comment by h1994st** [comment]
@BigDipper7 你是不是要疯了

本来想你昨天在课上就打开这个

**Comment by iViolinSolo** [comment]
@h1994st  好吧 我估计打开 我就要重点介绍这几个ID了2333反正我都认识
